### ISSUE TITLE
Conversations in 'undefined' dir?

### ISSUE THREAD

**Issue by SparksJ2** [sorentycho/blackmirror#6]
Call me suspicious, but does putting conversations in 'undefined' imply you forgot to set something? :)
_C:\Users\sparks\AppData\Local\Programs\blackmirror\undefined\conversations_

**Comment by sorentycho** [comment]
Weird. What value does `process.env.HOME` report for you if you evaluate that in a console window in the app?

**Comment by SparksJ2** [comment]
Interestingly it's picking up the style.css in both
_C:\Users\sparks\conversations\resources\_
AND
_C:\Users\sparks\AppData\Local\Programs\blackmirror\undefined\conversations\resources\_
and both sets of characters appear on the character picker with the appropriate combinatoric explosion.
```
process.env['HOME']
undefined
```
did you mean:
```
process.env['USERPROFILE']
"C:\Users\sparks"
```
or
```
process.env.HOMEPATH
"\Users\sparks"
```
which appears to be the windows versions?

(Note: my user dir is not actually sparks so sometimes I might paste it as either 'sparks' or 'sparky'.)

**Comment by sorentycho** [comment]
That's very weird what it's doing with searching both directories. Is Windows coalescing them from the app's perspective somehow? I know it does lots of crazy bindmounting magic, or did last time I touched a windows machine...

Anyway as of f9881ad631047d36d150880478fa0cb64f5a8697 I've updated this to use the `os` module to get the homedir, which *should* fix the original issue. Give it a try when you get a chance?

**Comment by sorentycho** [comment]
Try an `npm run build` from your source dir, it ought to build you an installer and leave it in dist, and then you can try the installer version...

Thank you for being my Windows CI facility...

**Comment by SparksJ2** [comment]
No worries.

I'm missing some stuff, I think, and I have no idea where the macOS thing below is coming from.

Total javascript/npm noob here! :)

```
> blackmirror@6.6.6 start C:\Users\sparks\Projects\bm667
C:\Users\sparks\Projects\bm667>npm run build

> blackmirror@6.6.6 build C:\Users\sparks\Projects\bm667
> electron-builder -mwl

electron-builder 19.34.1
Error: Build for macOS is supported only on macOS, please see https://electron.build/multi-platform-build
    at C:\Users\sparks\Projects\bm667\node_modules\electron-builder\src\packager.ts:222:15
    at next (native)
From previous event:
    at Packager.doBuild (C:\Users\sparks\Projects\bm667\node_modules\electron-builder\out\packager.js:344:11)
    at C:\Users\sparks\Projects\bm667\node_modules\electron-builder\src\packager.ts:186:52
    at next (native)
From previous event:
    at Packager.build (C:\Users\sparks\Projects\bm667\node_modules\electron-builder\out\packager.js:263:11)
    at C:\Users\sparks\Projects\bm667\node_modules\electron-builder\src\builder.ts:283:40
    at next (native)
From previous event:
    at build (C:\Users\sparks\Projects\bm667\node_modules\electron-builder\out\builder.js:63:21)
    at loadEnv.then (C:\Users\sparks\Projects\bm667\node_modules\electron-builder\src\cli\cli.ts:49:4)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Object.args [as handler] (C:\Users\sparks\Projects\bm667\node_modules\electron-builder\src\cli\cli.ts:49:4)
    at Object.runCommand (C:\Users\sparks\Projects\bm667\node_modules\yargs\lib\command.js:226:22)
    at Object.parseArgs [as _parseArgs] (C:\Users\sparks\Projects\bm667\node_modules\yargs\yargs.js:998:24)
    at Object.get [as argv] (C:\Users\sparks\Projects\bm667\node_modules\yargs\yargs.js:912:21)
    at Object.<anonymous> (C:\Users\sparks\Projects\bm667\node_modules\electron-builder\src\cli\cli.ts:43:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:496:3

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"

npm ERR! node v6.11.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! blackmirror@6.6.6 build: `electron-builder -mwl`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the blackmirror@6.6.6 build script 'electron-builder -mwl'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the blackmirror package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron-builder -mwl
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs blackmirror
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls blackmirror
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\sparks\Projects\bm667\npm-debug.log

C:\Users\sparks\Projects\bm667>
```
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@3.10.10
3 info using node@v6.11.4
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle blackmirror@6.6.6~prebuild: blackmirror@6.6.6
6 silly lifecycle blackmirror@6.6.6~prebuild: no script for prebuild, continuing
7 info lifecycle blackmirror@6.6.6~build: blackmirror@6.6.6
8 verbose lifecycle blackmirror@6.6.6~build: unsafe-perm in lifecycle true
9 verbose lifecycle blackmirror@6.6.6~build: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\sparks\Projects\bm667\node_modules\.bin;C:\Users\sparks\AppData\Roaming\npm;C:\Program Files\nodejs\;C:\Program Files (x86)\ActiveState Komodo Edit 10\;C:\Python27\;C:\Python27\Scripts;C:\Program Files\Haskell\bin;C:\Program Files\Haskell Platform\7.10.2-a\lib\extralibs\bin;C:\Program Files\Haskell Platform\7.10.2-a\bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Haskell Platform\7.10.2-a\mingw\bin;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files\Git\cmd;C:\Program Files\TortoiseHg\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\nodejs\;C:\Users\sparks\AppData\Roaming\cabal\bin;C:\Users\sparks\AppData\Roaming\npm
10 verbose lifecycle blackmirror@6.6.6~build: CWD: C:\Users\sparks\Projects\bm667
11 silly lifecycle blackmirror@6.6.6~build: Args: [ '/d /s /c', 'electron-builder -mwl' ]
12 silly lifecycle blackmirror@6.6.6~build: Returned: code: 4294967295  signal: null
13 info lifecycle blackmirror@6.6.6~build: Failed to exec build script
14 verbose stack Error: blackmirror@6.6.6 build: `electron-builder -mwl`
14 verbose stack Exit status 4294967295
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:920:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
15 verbose pkgid blackmirror@6.6.6
16 verbose cwd C:\Users\sparks\Projects\bm667
17 error Windows_NT 6.3.9600
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
19 error node v6.11.4
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error blackmirror@6.6.6 build: `electron-builder -mwl`
22 error Exit status 4294967295
23 error Failed at the blackmirror@6.6.6 build script 'electron-builder -mwl'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the blackmirror package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     electron-builder -mwl
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs blackmirror
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls blackmirror
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by sorentycho** [comment]
Oh huh, it can't build MacOS on Windows. I guess that makes sense. From the project dir, try `npx electron-builder -w` and see what you get?

**Comment by SparksJ2** [comment]
`npx electron-builder -w`
`'npx' is not recognized as an internal or external command, operable program or batch file.`
one `npm install -g npx` later...
_... cup of tea ..._
ok
`npx electron-builder -w`

```
C:\Users\sparks\Projects\bm667>npx electron-builder -w
C:\Users\sparks\Projects\bm667\node_modules\electron-builder\out\cli\cli.js
electron-builder 19.34.1
Rebuilding native production dependencies for win32:x64
Packaging for win32 x64 using electron 1.7.8 to dist\win-unpacked
Downloading tmp-5500-1-SHASUMS256.txt-1.7.8
[============================================>] 100.0% of 2.93 kB (2.93 kB/s)
Downloading winCodeSign-1.9.0, please wait
Building nsis installer (x64)
Downloading nsis-3.0.1.13, please wait
Downloading nsis-resources-3.3.0, please wait
```
Seems to have worked.

**Comment by SparksJ2** [comment]
oops wrong button

**Comment by SparksJ2** [comment]
oh derp it actually made an installer in /dist/
uninstalling, reinstalling.
looks good...
It's using `C:\Users\sparky\conversations\` now

**Comment by sorentycho** [comment]
Excellent! Closing.

Props and thanks some more for all this debug work. :1st_place_medal:
